### ISSUE TITLE
[Docker] Issue running docker

### ISSUE THREAD

**Issue by benjaminch** [davesag/mock-algolia#42]
Hello ! 

First, thanks a lot for this project, I was looking for something like so for a very long time :)

I was trying to launch the docker file locally but got the following error preventing container to run:

```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module './src/server'
Require stack:
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/index.js' ]
}
```

I think there is a simple fix in the Dockerfile, I'll have a look.

Cheers

**Comment by davesag** [comment]
fixed in version 0.0.9
